__author__ = 'roca'
# Read PrintRawPfile.txt file generated by 1_read_raw_pfiles_hdr.py script
# And extract some useful information :
# Fill a new file with :
# file with te list of all pfiles (.7) in the previous POOLS with:
# pathname, nameofbirth, MRI acq date, size in bytes, pathname

from rawpfile import printrawpfile_reader as prp
import os
import pandas

def printInfosFromPfileHdrInStream(printrawpfile_hdr_fname, stream):
    rawPfile_reader = prp.PrintRawPfileHdrReader(printrawpfile_hdr_fname)
    print >> stream, rawPfile_reader.getFormatedValuesInStringForCsvFile() +";" + \
                     printrawpfile_hdr_fname.replace('_','/').replace('.txt','.7')
    return True

workdir = '/home/roca/Documents/projets/flow/suivi/sujet_reorga_28_07_2015/workdir/'
printrawpfile_hdr_dir = os.path.join(workdir,'pfilesheader')
printrawpfile_hdr_fnames = os.listdir(printrawpfile_hdr_dir)
printrawpfile_hdr_fnames = map(lambda fname: os.path.join(printrawpfile_hdr_dir, fname),printrawpfile_hdr_fnames)
output_csv_fname = os.path.join(workdir,'infos_from_pfilesheader.csv')

f = open(output_csv_fname,"w")
reader = prp.PrintRawPfileHdrReader()
print >> f, reader.getFormatedKeysInStringForCsvFile()
map(lambda fname: printInfosFromPfileHdrInStream(fname,f),printrawpfile_hdr_fnames)
f.close()


# demain:
list_of_pfiles_info_fname = os.path.join(workdir,'pfile_path_and_size_29_07_2015_.csv')
pfiles_df = pandas.read_csv(list_of_pfiles_info_fname,sep = ";",encoding='utf-8')
