__author__ = 'roca'
# Read PrintRawPfile.txt file generated by 1_read_raw_pfiles_hdr.py script
# And extract some useful information :
# Fill a new file with :
# file with te list of all pfiles (.7) in the previous POOLS with:
# pathname, nameofbirth, MRI acq date, size in bytes, pathname

from rawpfile import printrawpfile_reader as prp
import os
import datatest as data

dataPath = os.path.dirname(data.__file__)

printRawPfileHdrFname = os.path.join(dataPath,'printraw.txt')

rawPfile_reader = prp.PrintRawPfileHdrReader(printRawPfileHdrFname)


print rawPfile_reader.getValuesInString()

